### ISSUE TITLE
vite创建的vue3项目， import from naive-ui/lib/_utils 编译报错

### ISSUE THREAD

**Issue by MYxu** [tusen-ai/naive-ui#3590]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
103.0.5060.114

### System and its version (系统及其版本)
window 10

### Node version (Node 版本)
14.18.3

### Reappearance link (重现链接)
https://codesandbox.io/s/wizardly-framework-1m6o4u?file=/src/App.vue:65-115

### Reappearance steps (重现步骤)
运行复现链接后，就直接编译报错了

### Expected results (期望的结果)
naive-ui/lib/_utils里面的方法可以正常import

### Actual results (实际的结果)
3:19:55 AM [vite] Internal server error: Missing "./lib/_utils" export in "naive-ui" package
  Plugin: vite:import-analysis
  File: /sandbox/src/App.vue
      at bail (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:33617:8)
      at resolve (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:33694:10)
      at resolveExports (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34717:12)
      at resolveDeepImport (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34735:31)
      at tryNodeResolve (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34452:20)
      at Context.resolveId (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34254:28)
      at async Object.resolveId (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35511:32)
      at async TransformContext.resolve (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35276:23)
      at async normalizeUrl (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40249:34)
      at async TransformContext.transform (file:///sandbox/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47) (x2)

### Remarks (补充说明)
vite版本：3.0.9

**Comment by doom-9** [comment]
<img width="478" alt="1661409993808" src="https://user-images.githubusercontent.com/110001160/186594272-dec3bdd3-85e1-46d1-aa62-b3feea906ade.png">
应该要在这定义导出下吧

**Comment by 07akioni** [comment]
> <img alt="1661409993808" width="478" src="https://user-images.githubusercontent.com/110001160/186594272-dec3bdd3-85e1-46d1-aa62-b3feea906ade.png">
> 
> 应该要在这定义导出下吧

不希望用户引入非入口的东西

@MYxu 有什么东西一定要从 lib 引入吗？如果从入口没有 export 的话可以提 feature request

**Comment by MYxu** [comment]
> > <img alt="1661409993808" width="478" src="https://user-images.githubusercontent.com/110001160/186594272-dec3bdd3-85e1-46d1-aa62-b3feea906ade.png">
> > 应该要在这定义导出下吧
> 
> 不希望用户引入非入口的东西
> 
> @MYxu 有什么东西一定要从 lib 引入吗？如果从入口没有 export 的话可以提 feature request

用到了 formatLength

**Comment by 07akioni** [comment]
> > > <img alt="1661409993808" width="478" src="https://user-images.githubusercontent.com/110001160/186594272-dec3bdd3-85e1-46d1-aa62-b3feea906ade.png">
> > > 应该要在这定义导出下吧
> > 
> > 
> > 不希望用户引入非入口的东西
> > @MYxu 有什么东西一定要从 lib 引入吗？如果从入口没有 export 的话可以提 feature request
> 
> 用到了 formatLength

这个是个内部工具函数，不希望被用户直接使用的，也不保证功能没有变化
