### ISSUE TITLE
NDatePicker built error with vite-ssg. 使用NDatePicker时，vite-ssg构建失败。

### ISSUE THREAD

**Issue by gjfLeo** [tusen-ai/naive-ui#4130]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Microsoft Edge (107.0.1418.62)

### System and its version (系统及其版本)
Windows 10

### Node version (Node 版本)
v16.16.0

### Reappearance link (重现链接)
https://github.com/gjfLeo/n-date-picker-vite-ssg-issue

### Reappearance steps (重现步骤)
```
npm i
npm run build
```

### Expected results (期望的结果)
构建成功。

### Actual results (实际的结果)
报错：
```
ReferenceError: document is not defined
    at queryElement (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\css-render\lib\utils.js:17:5)
    at mount (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\css-render\lib\mount.js:59:52)
    at Object.wrappedMount [as mount] (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\css-render\lib\c.js:14:45)
    at setup (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\vueuc\lib\binder\src\Follower.js:97:15)
    at callWithErrorHandling (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:15:22)
    at setupStatefulComponent (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5762:29)
    at setupComponent (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\@vue\runtime-core\dist\runtime-core.cjs.prod.js:5743:11)
    at renderComponentVNode (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:169:17)
    at renderVNode (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:296:22)
    at renderVNodeChildren (D:\git-liger\n-date-picker-vite-ssg-issue\node_modules\@vue\server-renderer\dist\server-renderer.cjs.prod.js:311:9)
```

### Remarks (补充说明)
将App.vue中使用NDatePicker的一行（第9行）删除后再执行`npm run build`，即可构建成功。

**Comment by censujiang** [comment]
I have same question

**Comment by censujiang** [comment]
请问一下您是如何完成NMessageProvider等组件能够被正常构建的？

**Comment by gjfLeo** [comment]
将 `ssgOptions.format` 设为 `cjs` 后可以使用 NButton 等组件；通过 `<client-only>` 可以使用 NDatePicker 等含弹窗的组件。但是 NConfigProvider 似乎仍然有问题（例如设置 inline-theme-disabled 等）。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
