### ISSUE TITLE
report error by toolbar's buttons when using click-preview on NImage component(NImage组件下预览模式工具栏使用报错)

### ISSUE THREAD

**Issue by MZ-Dlovely** [tusen-ai/naive-ui#4170]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Edge(108.0.1462.42)

### System and its version (系统及其版本)
Windows(22621.674)

### Node version (Node 版本)
v16.16.0

### Reappearance link (重现链接)
https://codesandbox.io/s/confident-mestorf-1ku368?file=/src/App.vue

### Reappearance steps (重现步骤)
1.  click the image for open preview view
2. click the button on the toolbar, like enlarge or shrink

### Expected results (期望的结果)
they're working on their way

### Actual results (实际的结果)
it report error by naiveui when it run with browser
``` js
// on edge console
Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at derivePreviewStyle (ImagePreview.js:262:152)
    at zoomIn (ImagePreview.js:236:17)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at HTMLElement.invoker (runtime-dom.esm-bundler.js:345:9)
```

### Remarks (补充说明)
i check the source file
"naive-ui/src/image/src/ImagePreview.tsx" use a lot of code like "imageContext?.previewedImgPropsRef"
and "naive-ui/src/image/src/Image.tsx" provide "imageContextKey" used "toRef(props, 'previewedImgProps')"
but previewedImgProps is undefined if default
so i can see the output like "imageContext: {previewedImgPropsRef: Ref<undefined>}"

**Comment by MZ-Dlovely** [comment]
i think just need set a default value like `{}` for  `previewedImgProps`

**Comment by MZ-Dlovely** [comment]
i see, thank u
