### ISSUE TITLE
ReferenceError: localStorage is not defined when using <n-theme-editor> in Nuxt3

### ISSUE THREAD

**Issue by ngthuongdoan** [tusen-ai/naive-ui#5070]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome (112.0.5615.49 (Official Build) (arm64))

### System and its version (系统及其版本)
MacOS (13.0.1)

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/nostalgic-tree-46z2st?welcome=true

### Reappearance steps (重现步骤)
Add <n-theme-editor> as example

### Expected results (期望的结果)
It's should work as normal

### Actual results (实际的结果)
ReferenceError: localStorage is not defined      02:42:31
    at setup (/project/sandbox/node_modules/naive-ui/lib/theme-editor/src/ThemeEditor.js:69:56)
    at callWithErrorHandling (/project/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)
    at setupStatefulComponent (/project/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7190:25)
    at setupComponent (/project/sandbox/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7151:36)
    at renderComponentVNode (/project/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:614:15)
    at renderVNode (/project/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:743:14)
    at renderVNodeChildren (/project/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:759:5)
    at renderElementVNode (/project/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:806:9)
    at renderVNode (/project/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:741:9)
    at renderComponentSubTree (/project/sandbox/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:698:7) {} setup function
[Vue warn]: Property "showPanel" was accessed during render but is not defined on instance.
[Vue warn]: Property "isMaximized" was accessed during render but is not defined on instance.

**Comment by fogine** [comment]
I experience the same issue when using theme overrides while server side rendering nuxt 3 application

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
