### ISSUE TITLE
Error 500 _cache is not defined when using n-layout & v-memo

### ISSUE THREAD

**Issue by turulix** [tusen-ai/naive-ui#5120]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Brave Version 1.56.14 Chromium: 115.0.5790.114 (Official Build) (64-bit)

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
18

### Reappearance link (重现链接)
https://stackblitz.com/edit/github-vztgqu-czm3lt?file=app.vue

### Reappearance steps (重现步骤)
Open the minimal reproduction.

### Expected results (期望的结果)
Its expected for it to simply render the page.

### Actual results (实际的结果)
500
_cache is not defined

at Module.renderList (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:2749:16)
at eval (./app.js:57:141)
at renderFnWithContext (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:762:13)
at normalizeChildren (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6951:34)
at createBaseVNode (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6762:5)
at _createVNode (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6839:10)
at createVNodeWithArgsTransform (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6716:10)
at h (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7445:12)
at Proxy.render (./node_modules/naive-ui/lib/layout/src/Layout.js:119:122)

**Comment by jizai1125** [comment]
https://github.com/nuxt/nuxt/issues/18749

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
