### ISSUE TITLE
统一设置主题色报错

### ISSUE THREAD

**Issue by zhangzhichaolove** [tusen-ai/naive-ui#5241]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
116.0.5845.179

### System and its version (系统及其版本)
macos 13.5.2 (22G91)

### Node version (Node 版本)
v18.7.0

### Reappearance link (重现链接)
https://naive-ui.github.io/

## 我使用外部主题色来复写UI的主题颜色。
```
<template>
  <n-config-provider
    :theme-overrides="themeOverrides"
  >
  <n-form
    ref="formRef"
    label-placement="left"
    label-width="auto"
    require-mark-placement="right-hanging"
    :style="{
      maxWidth: '640px',
    }"
  >
    <n-form-item label="Input" path="inputValue">
      <n-input v-model:value="model.inputValue" placeholder="Input" />
    </n-form-item>
  </n-form>
  </n-config-provider>
</template>
<script setup lang="ts">
  import { GlobalThemeOverrides } from "naive-ui";
import { ref } from "vue";
const model = ref({
  inputValue: "",
});
  const themeOverrides: GlobalThemeOverrides = {
    common: {
      primaryColor: 'var(--theme-color)',
    },
  };
</script>
```

### Expected results (期望的结果)
希望能够使用外部主题色。

### 得到以下错误：

```
index.js:120 Uncaught Error: [seemly/rgba]: Invalid color value var(--theme-color).
    at rgba (index.js:120:15)
    at changeColor (index.js:149:59)
    at self10 (light.js:15:362)
    at ReactiveEffect.fn (use-theme.js:53:95)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at ReactiveEffect.fn (Input.js:702:899)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1147:33)
    at unref (reactivity.esm-bundler.js:1026:29)
```

**Comment by zhangzhichaolove** [comment]
全局样式里面有申明主题色：

```
:root {
  --theme-color: #e95464;
}
```

**Comment by Sepush** [comment]
应该使用JS变量

**Comment by zhangzhichaolove** [comment]
也许未及时查看消息，看到后会及时回复。

**Comment by zhangzhichaolove** [comment]
当初用button组件测试过，改变主题色能动态改变按钮颜色，换成表单后，报了这个错，本以为可以偷懒，直接关联我外部定义的主题变量的。
改用pinia实现了。
