### ISSUE TITLE
500 document is not defined when using n-popover in Nuxt3

### ISSUE THREAD

**Issue by daselang** [tusen-ai/naive-ui#5817]
### 描述错误

1. WARN  [Vue warn]: Property "mergedTo" was accessed during render but is not defined on instance.
2.  500
  document is not defined
  
  at mount (./node_modules/css-render/lib/mount.js:59:52)
  at Object.wrappedMount [as mount] (./node_modules/css-render/lib/c.js:14:45)
  at setup (./node_modules/vueuc/lib/binder/src/Follower.js:97:15)
  at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:195:19)
  at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7554:25)
  at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7515:36)
  at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:15)
  at renderVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:755:14)
  at renderComponentSubTree (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:710:7)

### 复现步骤

1.  only copy and paste:
`   <n-popover>
          <template #trigger>f</template>
rrrr
     </n-popover>`
2.` import {NPopover,} from 'naive-ui';`
3. within Nuxt3 framwork.

### 最小复现链接

None

### 系统信息

```Shell
System:
    OS: macOS 14.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 29.50 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /usr/local/bin/node
    Yarn: 4.1.1 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    Watchman: 2023.12.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 123.0.6312.59
    Safari: 17.3.1
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1
    vue: ^3.4.21 => 3.4.21
```

### 使用的包管理器

yarn

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by daselang** [comment]
in node_modules/css_render/lib/utils.js,
the `document` object is not defined.
```
function queryElement(id) {
    return document.querySelector(`style[cssr-id="${id}"]`);
}
```
within the error stack,server-side render throwed the error 500 code.
so I set `ssr:false` in `nuxt.config.ts`,it works correct.

I hope you can fix it when ssr:true within the `Nuxt3`.

**Comment by johnson86tw** [comment]
@daselang Hey, I have the same error as this. But when I added the [plugin](https://github.com/07akioni/naive-ui-nuxt-demo/blob/main/plugins/naive-ui.ts) in plugins folder, it works well. It's documented [here](https://www.naiveui.com/en-US/os-theme/docs/ssr) in the third process.

**Comment by daselang** [comment]
@johnson86tw thanks for providing me the official resulotion.It works.
