### ISSUE TITLE
build:package打包失败

### ISSUE THREAD

**Issue by 18626428291** [tusen-ai/naive-ui#6178]
### 描述错误

 ./es/affix/src/styles
PS C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main> pnpm build:package

> naive-ui@2.39.0 build:package C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main
> pnpm run gen-version && pnpm run clean && pnpm run gen-volar-dts && tsc -b --force tsconfig.esm.json && node scripts/pre-build/pre-cjs-build.js && tsc -b --force tsconfig.cjs.json && rollup -c && node scripts/post-build && rimraf {es,lib}/*.tsbuildinfo

> naive-ui@2.39.0 gen-version C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main
> node scripts/gen-version

> naive-ui@2.39.0 clean C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main
> rimraf site lib es dist node_modules/naive-ui themes/tusimple/es themes/tusimple/lib

> naive-ui@2.39.0 gen-volar-dts C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main
> esbuild scripts/gen-component-declaration.js --bundle --platform=node --tsconfig=tsconfig.esbuild.json | node

C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\src\index.ts → dist/index.js...
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
(!) Circular dependencies
node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/traps.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js
src/dropdown/src/DropdownMenu.tsx -> src/dropdown/src/DropdownGroup.tsx -> src/dropdown/src/DropdownOption.tsx -> src/dropdown/src/DropdownMenu.tsx
src/menu/src/utils.tsx -> src/menu/src/MenuOptionGroup.tsx -> src/menu/src/utils.tsx
src/menu/src/utils.tsx -> src/menu/src/Submenu.tsx -> src/menu/src/utils.tsx
created dist/index.js in 12.2s

C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\src\index.ts → dist/index.prod.js...
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
(!) Circular dependencies
node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/traps.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js
src/dropdown/src/DropdownMenu.tsx -> src/dropdown/src/DropdownGroup.tsx -> src/dropdown/src/DropdownOption.tsx -> src/dropdown/src/DropdownMenu.tsx
src/menu/src/utils.tsx -> src/menu/src/MenuOptionGroup.tsx -> src/menu/src/utils.tsx
src/menu/src/utils.tsx -> src/menu/src/Submenu.tsx -> src/menu/src/utils.tsx
created dist/index.prod.js in 13.8s

C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\src\index.ts → dist/index.mjs...
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
(!) Circular dependencies
node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/traps.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js
src/dropdown/src/DropdownMenu.tsx -> src/dropdown/src/DropdownGroup.tsx -> src/dropdown/src/DropdownOption.tsx -> src/dropdown/src/DropdownMenu.tsx
src/menu/src/utils.tsx -> src/menu/src/MenuOptionGroup.tsx -> src/menu/src/utils.tsx
src/menu/src/utils.tsx -> src/menu/src/Submenu.tsx -> src/menu/src/utils.tsx
created dist/index.mjs in 9.8s

C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\src\index.ts → dist/index.prod.mjs...
[BABEL] Note: The code generator has deoptimised the styling of C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\lodash.js as it exceeds the max of 500KB.
(!) Circular dependencies
node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/traps.js -> node_modules/.pnpm/evtd@0.2.4/node_modules/evtd/es/delegate.js
src/dropdown/src/DropdownMenu.tsx -> src/dropdown/src/DropdownGroup.tsx -> src/dropdown/src/DropdownOption.tsx -> src/dropdown/src/DropdownMenu.tsx
src/menu/src/utils.tsx -> src/menu/src/MenuOptionGroup.tsx -> src/menu/src/utils.tsx
src/menu/src/utils.tsx -> src/menu/src/Submenu.tsx -> src/menu/src/utils.tsx
created dist/index.prod.mjs in 13.5s
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError: C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\es\calendar\src\Calendar.js: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:429:7)
    at guessFullPath (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\scripts\post-build\complete-path.js:162:27)
    at parseSource (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\scripts\post-build\complete-path.js:145:9)
    at PluginPass.ImportDeclaration (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\scripts\post-build\complete-path.js:21:38)
    at newFn (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\visitors.js:160:14)
    at NodePath._call (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\path\context.js:47:20)
    at NodePath.call (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\path\context.js:37:18)
    at NodePath.visit (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\path\context.js:83:31)
    at TraversalContext.visitQueue (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitMultiple (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\context.js:61:17)
    at TraversalContext.visit (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\context.js:110:19)
    at traverseNode (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at NodePath.visit (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\path\context.js:89:52)
    at TraversalContext.visitQueue (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at traverse (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+traverse@7.24.8\node_modules\@babel\traverse\lib\index.js:52:34)
    at transformFile (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+core@7.24.9\node_modules\@babel\core\lib\transformation\index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+core@7.24.9\node_modules\@babel\core\lib\transformation\index.js:24:12)
    at run.next (<anonymous>)
    at transform (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\@babel+core@7.24.9\node_modules\@babel\core\lib\transform.js:22:33)
    at transform.next (<anonymous>)
    at step (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\gensync@1.0.0-beta.2\node_modules\gensync\index.js:261:32)
    at C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\gensync@1.0.0-beta.2\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\gensync@1.0.0-beta.2\node_modules\gensync\index.js:223:11)
    at C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\gensync@1.0.0-beta.2\node_modules\gensync\index.js:50:45
    at step (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\gensync@1.0.0-beta.2\node_modules\gensync\index.js:287:14)
    at C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\gensync@1.0.0-beta.2\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\Users\徐家俊\Downloads\naive-ui-main\naive-ui-main\node_modules\.pnpm\gensync@1.0.0-beta.2\node_modules\gensync\index.js:223:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.20.2

遇到两个问题：
1.第一遍是测试 test 过不去
2.第二遍就是The "path" argument must be of type string. Received undefined

在macos下 会遇到 date-fns找不到 以及 lodash依赖问题

### 复现步骤

下载最新的包代码
执行pnpm build:package命令

### 最小复现链接

1

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600KF
    Memory: 43.07 GB / 63.85 GB
  Binaries:
    Node: 18.20.2 - ~\AppData\Local\Volta\tools\image\node\18.20.2\node.EXE
    npm: 10.5.0 - ~\AppData\Local\Volta\tools\image\node\18.20.2\npm.CMD
    pnpm: 9.6.0 - C:\Program Files\Volta\pnpm.EXE
  Browsers:
    Edge: Chromium (126.0.2592.113)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vue: ~3.4.15 => 3.4.33
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by 18626428291** [comment]
![image](https://github.com/user-attachments/assets/97193da4-5850-46b1-9ed7-fc6bc92d3abe)
这是打包失败后产物
尝试 压缩成tar.gz文件 导入新vue3项目
![image](https://github.com/user-attachments/assets/9c8040e9-f482-4524-902c-7c6ad7b5e9f2)
运行错误如图
![image](https://github.com/user-attachments/assets/77b86328-514a-47db-8d2c-4e4f3fe9cff2)

**Comment by 18626428291** [comment]
![image](https://github.com/user-attachments/assets/7de2f5a2-8250-4500-b98f-bc493afa4017)

**Comment by jahnli** [comment]
重新最新代码重试下
